from .maps import maps
from .location import location
from .piece import piece
from .add_piece import add_piece
from .remove_piece import remove_piece
from .register import register
from .profile import profile
from .gear import gear
from .gear_categories import gearcat